version: '3.9'
services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  mongo:
    image: mongo:5.0
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  neo4j:
    image: neo4j:4.4
    environment:
      NEO4J_AUTH: ${NEO4J_AUTH}
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo4j_data:/data

  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data

  orion:
    image: fiware/orion-ld:latest
    depends_on:
      - mongo
    command: -dbhost mongo
    ports:
      - "1026:1026"

  mysql-adapter:
    build:
      context: ./services/mysql-adapter
    ports:
      - "8001:8000"
    depends_on:
      - mysql
    networks:
      - default

  minio-adapter:
    build:
      context: ./services/minio-adapter
    container_name: digital-twin-minio-adapter
    ports:
      - "8000:8000"  #  外部访问端口
    depends_on:
      - minio
    networks:
      - default
    restart: always

  neo4j-adapter:
    build:
      context: ./services/neo4j-adapter
    ports:
      - "8002:8000"
    depends_on:
      - neo4j
    networks:
      - default
    environment:
      - NEO4J_URL=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=test

  orion-ld-adapter:
    build:
      context: ./services/orion-ld-adapter
    ports:
      - "8003:8000"
    depends_on:
      - orion
    networks:
      - default
    environment:
      - ORION_URL=http://orion:1026


volumes:
  mysql_data:
  mongo_data:
  neo4j_data:
  minio_data:
